name: Print the text file

on:
    push:
      branches:
        - main

jobs:
    print_text_file:
        runs-on: ubuntu-latest 

        steps: 
        - name: Clone The Repository
          uses: actions/checkout@v2
        -   name: Read the file
            run: |
                ls -la
                cat hello.txt
        - name: Making Folder
          run: |
                mkdir -p GitHub
        - name: Check folder
          run: |
                ls -la